### ISSUE TITLE
Missing process version information

### ISSUE THREAD

**Issue by vti** [team-at-cpan/OpenTracing#5]
Version is empty, since OpenTracing::Tracer doesn't actually have it. It should be probably taken from the main package.

```
bless( {
                 'process' => bless( {
                                       'ip' => '192.168.1.1',
                                       'pid' => 336478,
                                       'tracer.version' => 'perl-OpenTracing-'
                                     }, 'OpenTracing::Process' ),
                 'current_span' => [],
                 'span_completion_callbacks' => []
               }, 'OpenTracing::Tracer' );
```

**Comment by vti** [comment]
I guess this is only working when it's prepared for the release, VERSION in injected automatically. That's a bit confusing. But feel free to close this issue.

**Comment by tm604** [comment]
It is indeed confusing, so I've put some extra logic in f898110f8e87363cc9e656cab4ecb2cc759b477e in an attempt to make this more useful. Thanks for the report!
